server:
  port: 8084
  servlet:
    context-path: /api
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pic_memories
    username: root
    password: Dw990831

    # session 失效时间(分钟)
  session:
    timeout: 86640
    store-type: redis
    # redis 配置
  redis:
    port: 6379
    host: localhost
    database: 0

knife4j:
  enable: true
  openapi:
    title: PicMemories 接口文档
    description: PicMemories 壁纸分享小程序
    concat: 3348407547@qq.com
    url: https://deng-2022.gitee.io/blog/
    version: 1.0
    license: Apache 2.0
    group:
      test1:
        group-name: 壁纸分享

mybatis-plus:
  global-config:
    # 逻辑删除
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)


  # 开启SQL查询日志
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 阿里云OSS配置
aliyun:
  oss:
    end-point: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5t9bAnh9zthSmzTPARM4
    access-key-secret: BwV3YKjHp4W2Hk6hYXx1FLbDMO3Qnz
    bucket-name: pic-memories


